image: docker

services:
  - docker: dind

before_script:
  - export
  - docker login registry.gitlab.com --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

build: 
  script:
    - docker pull registry.gitlab.com/daniladaniladanila/skillbox:latest
    - docker build . --tag registry.gitlab.com/daniladaniladanila/skillbox:$CI_BUILD_REF --tag --tag registry.gitlab.com/daniladaniladanila/skillbox:latest 
    - docker push registry.gitlab.com/daniladaniladanila/skillbox:latest
    - docker push registry.gitlab.com/daniladaniladanila/skillbox:$CI_BUILD_REF

    # - docker build -t registry.gitlab.com/daniladaniladanila/skillbox .
    # - docker push registry.gitlab.com/daniladaniladanila/skillbox