image: docker

services:
  - docker: dind

before_script:
  - export
  - docker login registry.gitlab.com --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

build: 
  script:
    - docker build . --tag registry.gitlab.com/daniladaniladanila/skillbox
    - docker push registry.gitlab.com/daniladaniladanila/skillbox
    
    # - docker build -t registry.gitlab.com/daniladaniladanila/skillbox .
    # - docker push registry.gitlab.com/daniladaniladanila/skillbox